agents/urls.py
from django.urls import path
from .views import (
    AgentListView,
    AgentDetailView, 
    AgentUpdateView,
    AgentCreateView,
    AgentDeleteView
)

app_name = 'agents'

urlpatterns = [
    path('', AgentListView.as_view(), name='agent_list'),
    path('create/', AgentCreateView.as_view(), name='agent_create'),
    path('detail/<int:pk>/', AgentDetailView.as_view(), name='agent_detail'),
    path('update/<int:pk>/', AgentUpdateView.as_view(), name='agent_update'),
    path('delete<int:pk>/', AgentDeleteView.as_view(), name='agent_delete')
]

dj_crm/urls.py
from django.contrib.auth.views import (LoginView, 
LogoutView, 
PasswordResetView,
PasswordResetDoneView,
PasswordResetCompleteView,
PasswordResetConfirmView,
)
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from leads.views import SignupView, home_page



urlpatterns = [
    path('', home_page, name='home'),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset-password', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-complete', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('signup/', SignupView.as_view(), name='signup')
]


if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

leads/urls.py
from django.urls import path
from .views import (
    LeadListView,
    LeadDetailView,
    LeadCreateView,
    LeadUpdateView,
    LeadDeleteView,
    AssignAgentView,
    CategoryListView,
    CategoryDetailView,
    CategoryUpdateView,
  

) 
app_name = 'leads'

urlpatterns = [


    path('', LeadListView.as_view(), name='lead_list'),
    path('<int:pk>/', LeadDetailView.as_view(), name='lead_detail'),
    path('update/<int:pk>/', LeadUpdateView.as_view(), name='lead_update'),
    path('delete/<int:pk>/', LeadDeleteView.as_view(), name='lead_delete'),
    path('assign-lead/<int:pk>/', AssignAgentView.as_view(), name='assign-lead'),
    path('create/', LeadCreateView.as_view(), name='create_lead'),
    path('category-list/', CategoryListView.as_view(), name='category-list'),
    path('<int:pk>/category-detail/', CategoryDetailView.as_view(), name='category-detail'),
    path('<int:pk>/category-update/', CategoryUpdateView.as_view(), name='category-update'),

]

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from django import forms
from django.contrib.auth import get_user_model


User = get_user_model()

class AgentCreateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'username', 'first_name', 'last_name']

agents/views.py
import random

from django.shortcuts import render, reverse
from django.views import generic
from leads.models import Agent
from .forms import AgentCreateForm
from django.contrib.auth.mixins import LoginRequiredMixin
from .mixins import OrganiserAndLoginRequiredMixin
from django.core.mail import send_mail


class AgentListView(OrganiserAndLoginRequiredMixin, generic.ListView):
    template_name = 'agents/agent-list.html'

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)


class AgentCreateView(OrganiserAndLoginRequiredMixin, generic.CreateView):
    template_name = 'agents/agent-create.html'
    form_class = AgentCreateForm

    def get_success_url(self):
        return reverse('agents:agent_list')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_agent=True
        user.is_organiser = False
        user.set_password(f"{random.randint(0, 1000000)}")
        user.save()
        send_mail(subject='You were made an agent', 
            message='You have an agent account in DJ-CRM, please follow the link attatched to this email to login and get started, We hope to see you..',
            from_email='us@django.com',
            recipient_list=(user.email,))
        
        Agent.objects.create(
            user=user,
            organisation=self.request.user.userprofile
        )
       
        return super(AgentCreateView, self).form_valid(form)
    

    
class AgentDetailView(OrganiserAndLoginRequiredMixin, generic.DeleteView):
    template_name = 'agents/agent-detail.html'
    context_object_name = 'agent'

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)

class AgentUpdateView(OrganiserAndLoginRequiredMixin, generic.UpdateView):
    template_name = 'agents/agent-update.html'
    form_class = AgentCreateForm

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)

    def get_success_url(self):
        return reverse('agents:agent_list')


class AgentDeleteView(OrganiserAndLoginRequiredMixin, generic.DeleteView):
    template_name = 'agents/agent-delete.html'
    
    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)
    
    def get_success_url(self):
        return reverse('agents:agent_list')

templates/agents/agent-create.html
{% extends 'base.html' %}

{% load tailwind_filters %}

{% block content %}
    <div class="max-w-lg mx-auto">
    <form method="post">
    {% csrf_token %}
    {{form|crispy}}

    <button class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 my-1 rounded-md">Create Agent</button>
    </form>
</div>
{% endblock content %}

templates/agents/agent-delete.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-2/3 flex flex-col sm:flex-row sm:items-center items-start mx-auto">
   
      <h1 class="flex-grow sm:pr-16 text-2xl font-medium title-font text-gray-900">Are you sure you want to delete this Agent?
.</h1>
       <form method="post">
    {% csrf_token %}
    {{form.as_p}}
      <button type="submit" class="flex-shrink-0 text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg mt-10 sm:mt-0">Delete</button>

    </form>
    </div>
  </div>
</section>
{% endblock content %}

templates/agents/agent-detail.html
{% extends 'base.html' %}

{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">Agent</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{agent.first_name}} {{agent.last_name}}</h1>
        <div class="flex mb-4">
          <a href="{% url 'agents:agent_detail' agent.pk%}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Overview</a>
          <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"></a>
          <a href="{% url 'agents:agent_update' agent.pk%}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update</a>
        </div>
        <p class="agenting-relaxed mb-4">This is the information about this agent</p>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Name</span>
          <span class="ml-auto text-gray-900">{{agent.user.username}}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Location</span>
          <span class="ml-auto text-gray-900">{{agent.loacation}}</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500">Phone</span>
          <span class="ml-auto text-gray-900">{{agent.phone}}</span>
        </div>
        <div class="flex">
       
          <button class="w-full mx-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded"> <a href="{% url 'agents:agent_delete' agent.pk %}">Delete</a> </button>
         
        </div>
      </div>
      {% if agent.image %}
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="{{agent.image.url}}">
      {% else %}
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
      {% endif %}
    </div>
  </div>
</section>
{% endblock content %}

templates/agents/agent-list.html
{% extends 'base.html' %}

{% block content %}

<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
    <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
        <div>
            <h1 class="text-4xl text-gray-800">Agents</h1>
        </div>
        <div>
            <a class="text-gray-500 hover:text-blue-500" href="{% url 'agents:agent_create' %}">Create Agent</a>
        </div>
    </div>
    <div class="flex flex-wrap -m-4">
    {% for agent in object_list %}
      <div class="p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
          <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{agent.user.username}}</h2>
            <p class="agenting-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.</p>
            <a href="{% url 'agents:agent_detail' agent.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">View agent
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
  </div>
</section>




{% endblock content %}

templates/agents/agent-update.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/1 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">Agent</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{agent.user.username}} </h1>
        <div class="flex mb-4">
          <a href="{% url 'agents:agent_detail' agent.pk%}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Overview</a>
          <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"></a>
          <a href="{% url 'agents:agent_update' agent.pk%}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Update</a>
        </div>
       
        <div class="max-w-lg mx-auto">
          <form method='post'>
          {% csrf_token %}
          {{form|crispy}}
      
            <button class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 my-1 rounded-md">Update Agent</button>
          </form>
        </div>      
      
      </div>
    
    </div>
  </div>
</section>



{% endblock content %}