dj_crm/urls.py
from django.contrib.auth.views import (LoginView, 
LogoutView, 
PasswordResetView,
PasswordResetDoneView,
PasswordResetCompleteView,
PasswordResetConfirmView,
)
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from leads.views import SignupView, home_page



urlpatterns = [
    path('', home_page, name='home'),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset-password', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-complete', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('signup/', SignupView.as_view(), name='signup')
]


if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

leads/urls.py
from django.urls import path
from .views import (
    LeadListView,
    LeadDetailView,
    LeadCreateView,
    LeadUpdateView,
    LeadDeleteView,
    AssignAgentView,
    CategoryListView,
    CategoryDetailView,
    CategoryUpdateView,
  

) 
app_name = 'leads'

urlpatterns = [


    path('', LeadListView.as_view(), name='lead_list'),
    path('<int:pk>/', LeadDetailView.as_view(), name='lead_detail'),
    path('update/<int:pk>/', LeadUpdateView.as_view(), name='lead_update'),
    path('delete/<int:pk>/', LeadDeleteView.as_view(), name='lead_delete'),
    path('assign-lead/<int:pk>/', AssignAgentView.as_view(), name='assign-lead'),
    path('create/', LeadCreateView.as_view(), name='create_lead'),
    path('category-list/', CategoryListView.as_view(), name='category-list'),
    path('<int:pk>/category-detail/', CategoryDetailView.as_view(), name='category-detail'),
    path('<int:pk>/category-update/', CategoryUpdateView.as_view(), name='category-update'),

]

leads/models.py
from django.db import models
from django.shortcuts import reverse
from django.utils import timezone
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    is_organiser = models.BooleanField(default=True)
    is_agent = models.BooleanField(default=False)
    


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username
    

class Lead(models.Model):
    first_name = models.CharField(max_length=200)
    last_name   = models.CharField(max_length=200)
    age         = models.IntegerField(default=0)
    agent       = models.ForeignKey('Agent', null=True, blank=True, on_delete=models.SET_NULL)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    category = models.ForeignKey("Category", related_name='leads', null=True, blank=True, on_delete=models.SET_NULL)
    description = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    phone_number = models.CharField(max_length=20)
    email = models.EmailField(null=True, blank=True)


    def __str__(self):
        return self.first_name


    def get_absolute_url(self):
        return reverse("leads:lead_detail", kwargs={"pk": self.pk})

    def get_update_url(self):
        return reverse("leads:lead_update", kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse("leads:lead_delete", kwargs={"pk": self.pk})
    
       
    


class Agent(models.Model):  
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True, upload_to='agent-pics/')
    location = models.CharField(max_length=250, null=True, blank=True)
    phone = models.CharField(max_length=250, null=True, blank=True)
    
    
    def __str__(self):
        return self.user.username
    

class Category(models.Model):
    name = models.CharField(max_length=250)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    

leads/forms.py
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth import get_user_model
from django import forms
from .models import Lead, Agent

User = get_user_model()

class LeadCreateForm(forms.ModelForm):
    
    class Meta:
        model = Lead
        fields = (
        "first_name",
        "last_name",
        "age", 
        "agent",
        "category",
        "description",
    
        "phone_number",
        "email",
)


class CreateLeadForm(forms.Form):
    first_name = forms.CharField(max_length=300)
    last_name = forms.CharField(max_length=300)
    age = forms.IntegerField(min_value=20)



class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",)
        field_classes = {'username': UsernameField}
        

class AssignAgentForm(forms.Form):
    agent = forms.ModelChoiceField(queryset=Agent.objects.none())

    def __init__(self, *args, **kwargs):
        request = kwargs.pop('request')
        agents = Agent.objects.filter(organisation=request.user.userprofile)
        super(AssignAgentForm, self).__init__(*args, **kwargs)
        self.fields['agent'].queryset = agents


class LeadCategoryUpdateForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = ['category']

leads/views.py
from django.shortcuts import render, redirect, reverse
from .models import User, Lead, Agent, Category
from django.http import Http404, HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import LeadCreateForm, CreateLeadForm, LeadCategoryUpdateForm
from .forms import CustomUserCreationForm, AssignAgentForm
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView, View, FormView
# from django.contrib.auth.views import 
from .mixins import OrganiserAndLoginRequiredMixin


def home_page(request):
    template_name = "pages/home.html"
    context = {
        'title': "Home Page",
    }

    return render(request, template_name, context)
    

class SignupView(CreateView):
    template_name = 'registration/signup.html'
    form_class = CustomUserCreationForm

    
class LeadListView(LoginRequiredMixin, ListView):
    template_name = 'leads/lead_list.html'
    context_object_name = 'leads'

    def get_queryset(self):
        user = self.request.user
        # filter the for the entire Organisation
        if user.is_organiser:
            queryset = Lead.objects.filter(organisation=user.userprofile, agent__isnull=False)
        else:
            # filter for logged in user
            queryset = Lead.objects.filter(organisation=user.agent.organisation, agent__isnull=False)
            queryset = queryset.filter(agent__user=user)
        
        return queryset

    def get_context_data(self, *args, **kwargs):
        user = self.request.user
        context = super(LeadListView, self).get_context_data(**kwargs)
        if user.is_organiser is False:
            context.update({
                'organisation': user.agent.organisation
            })
        if user.is_organiser:
            queryset = Lead.objects.filter(organisation=user.userprofile, agent__isnull=True)


            context.update({
                'unassigned_leads': queryset,
                
            })

        return context


class LeadDetailView(LoginRequiredMixin, DetailView):

    template_name = 'leads/lead_detail.html'
    context_object_name = 'lead'
    
    def get_queryset(self):
        user = self.request.user
    # filter the for the entire Organisation
        if user.is_organiser:
            queryset = Lead.objects.filter(organisation=user.userprofile)
        else:
            # filter for logged in user
            queryset = Lead.objects.filter(organisation=user.agent.organisation)
            queryset = queryset.filter(agent__user=user)
        
        return queryset
    

    

class LeadCreateView(OrganiserAndLoginRequiredMixin, CreateView):
    form_class = LeadCreateForm
    template_name = 'leads/lead_create.html'



    def form_valid(self, form):
        lead = form.save(commit=False)
        lead.organisation = self.request.user.userprofile
        print(lead.first_name, lead.organisation)
        lead.save()
        return super(LeadCreateView, self).form_valid(form)
    def get_success_url(self):
        return reverse("leads:lead_list")     


class LeadUpdateView(OrganiserAndLoginRequiredMixin, UpdateView):
    template_name = 'leads/leads_update.html'
    form_class = LeadCreateForm
    
    def get_queryset(self):
        user = self.request.user
    # filter the for the entire Organisation
        if user.is_organiser:
            queryset = Lead.objects.filter(organisation=user.userprofile)
        return queryset

    def get_success_url(self):
        return reverse('leads:lead_list')

   
class LeadDeleteView(OrganiserAndLoginRequiredMixin, DeleteView):
    template_name = 'leads/lead_delete.html'

    def get_queryset(self):
        user = self.request.user
    # filter the for the entire Organisation
        if user.is_organiser:
            queryset = Lead.objects.filter(organisation=user.userprofile)
        return queryset 

    def get_success_url(self):
        return reverse('leads:lead_list')

class AssignAgentView(OrganiserAndLoginRequiredMixin, FormView):
    template_name = 'leads/assign-agent.html'
    form_class = AssignAgentForm

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super(AssignAgentView, self).get_form_kwargs(*args, **kwargs)
        kwargs.update({
            'request': self.request
        })

        return kwargs

    def get_success_url(self):
        return reverse('leads:lead_list')

    def form_valid(self, form):
        print(form.cleaned_data.get('agent'))
        agent = form.cleaned_data.get('agent')
        lead = Lead.objects.get(id=self.kwargs['pk'])
        lead.agent=agent
        lead.save()
        return super(AssignAgentView, self).form_valid(form)


class CategoryListView(LoginRequiredMixin, ListView):
    template_name = 'leads/category-list.html'

    context_object_name = 'categories'

    def get_queryset(self):
        user = self.request.user
        # Getting the initail queryset 
        if user.is_organiser:
            queryset = Category.objects.filter(organisation=user.userprofile)
        else:
            queryset = Category.objects.filter(organisation=user.agent.organisation)

        return queryset 

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super(CategoryListView, self).get_context_data(**kwargs)

        if user.is_organiser:
            queryset = Lead.objects.filter(organisation=user.userprofile)
        else:
            queryset = Lead.objects.filter(organisation=user.agent.organisation)
        
        context.update({
            'unassigned_lead_count': queryset.filter(category__isnull=True).count()
        })
        return context
    

class CategoryDetailView(LoginRequiredMixin, DetailView):

    template_name = 'leads/category-detail.html'
    context_object_name = 'category'

    def get_queryset(self):
        user = self.request.user
        # Getting the initail queryset 
        if user.is_organiser:
            queryset = Category.objects.filter(organisation=user.userprofile)
        else:
            queryset = Category.objects.filter(organisation=user.agent.organisation)

        return queryset 

    def get_context_data(self, **kwargs):
        context = super(CategoryDetailView, self).get_context_data(**kwargs)
        leads = self.get_object().leads.all()
        context.update({
            'leads': leads
        })
        print(leads)
        return context


class CategoryUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'leads/category-update.html'
    form_class = LeadCategoryUpdateForm


    def get_queryset(self):
        user = self.request.user

        # Getting the initail queryset for the entire organisation
        if user.is_organiser:
            queryset = Lead.objects.filter(organisation=user.userprofile)
        else:
            queryset = Lead.objects.filter(organisation=user.agent.organisation)
            # Filter for the agent that is logged in
            queryset = queryset.filter(agent__user=user)
        
        return queryset
    
    def get_success_url(self):
        return reverse('leads:lead_detail', kwargs={'pk': self.get_object().id})

templates/leads/assign-agent.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
Assign this lead to an Agent
<form method="post">
{% csrf_token %}
{{form|crispy}}
<input type="submit" value="Create Lead">
</form>
{% endblock content %}

templates/leads/category-detail.html
{% extends 'base.html' %}

{% block content %}

<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-col text-center w-full mb-20">
      <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900"> {{category.name}}</h1>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base">These categories segment the leads</p>
    </div>
    <div class="lg:w-2/3 w-full mx-auto overflow-auto">
      <table class="table-auto w-full text-left whitespace-no-wrap">
        <thead>
          <tr>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Leads</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Age</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Date Joined</th>
        
          </tr>
        </thead>
        <tbody>
        
        {% for lead in leads%}
          <tr>
            <td class="px-4 py-3 hover:text-blue-300">
            <a href="{% url 'leads:lead_detail' lead.pk %}">{{lead.first_name}}</a>
            </td>
            <td class="px-4 py-3">{{lead.age}}</td>
            <td class="px-4 py-3">{{lead.date_added}}</td>

            
          
          </tr>
        {% endfor %}
         
        </tbody>
      </table>
    </div>
 
  </div>
</section>


{% endblock content %}

templates/leads/category-list.html
{% extends 'base.html' %}

{% block content %}

<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-col text-center w-full mb-20">
      <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900"> Categories</h1>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base">These categories segment the leads</p>
    </div>
    <div class="lg:w-2/3 w-full mx-auto overflow-auto">
      <table class="table-auto w-full text-left whitespace-no-wrap">
        <thead>
          <tr>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Name</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Lead Count</th>
        
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="px-4 py-3">Unassigned</td>
            <td class="px-4 py-3">{{unassigned_lead_count}}</td>
          
          </tr>
        {% for category in categories%}
          <tr>
         
            <td class="px-4 py-3"> <a href="{% url 'leads:category-detail' category.pk%}">{{category.name}} </a></td>
            <td class="px-4 py-3">{{forloop.counter}}</td>
          
          </tr>
        {% endfor %}
         
        </tbody>
      </table>
    </div>
 
  </div>
</section>


{% endblock content %}

templates/leads/category-update.html
{% extends 'base.html' %}
{% load tailwind_filters %}


{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto ">
      <div class="lg:w-1/1 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">Lead</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{lead.first_name}} {{lead.last_name}}</h1>
        <div class="flex mb-4">
          <a href="{% url 'leads:lead_detail' lead.pk%}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Overview</a>
          <a href="{% url 'leads:category-update' lead.pk%}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Category</a>
          <a href="{% url 'leads:lead_update' lead.pk%}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update</a>
        </div>

        flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1
        
        <form method='post'>
          {% csrf_token %}
          {{form|crispy}}
          
          <button class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 my-1 rounded-md">Update Category</button>
        </form>
        <div class="flex">

        
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}
 

templates/leads/lead_create.html
{% extends 'base.html' %}
{% load tailwind_filters %}


{% block content %}
<div class="max-w-lg mx-auto">
<form method="post">
{% csrf_token %}
{{form|crispy}}
 <button class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 my-1 rounded-md">Create Lead</button>
</form>
</div>
{% endblock content %}

templates/leads/lead_delete.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-2/3 flex flex-col sm:flex-row sm:items-center items-start mx-auto">
   
      <h1 class="flex-grow sm:pr-16 text-2xl font-medium title-font text-gray-900">Are you sure you want to delete the Lead?
.</h1>
       <form method="post">
    {% csrf_token %}
    {{form|crispy}}
      <button type="submit" class="flex-shrink-0 text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg mt-10 sm:mt-0">Delete</button>
    </form>
    </div>
  </div>
</section>
{% endblock content %}

templates/leads/lead_detail.html
{% extends 'base.html' %}

{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto">
      <div class="lg:w-4/4 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">Lead {{agent.organisation}}</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{lead.first_name}} {{lead.last_name}}</h1>
        <div class="flex mb-4">
          <a href="{% url 'leads:lead_detail' lead.pk%}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Overview</a>
          <a href="{% url 'leads:category-update' lead.pk%}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Category</a>
          <a href="{% url 'leads:lead_update' lead.pk%}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update</a>
        </div>
        <p class="leading-relaxed mb-4">{{lead.description}}</p>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500 px-5">Age</span>
          <span class="ml-auto px-5 text-gray-900">{{lead.age}}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500 px-5 ">Agent</span>
          <span class="ml-auto px-5 text-gray-900">{{lead.agent}}</span>
        </div>
        <div class="flex border-t border-b border-gray-200 py-2">
          <span class="text-gray-500 px-5 ">Phone</span>
          <span class="ml-auto px-5 text-gray-900">+237{{lead.phone_number}}</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500 px-5 ">E-mail</span>
          <span class="ml-auto px-5 text-gray-900">{{lead.email}}</span>
        </div>
        <div class="flex">

          {% if request.user.is_organiser %}
          <button class="w-full mx-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded"> <a href="{% url 'leads:lead_delete' lead.pk %}">Delete</a> </button>
        
          {% endif %}
        </div>
      </div>
      
    </div>
  </div>
</section>
{% endblock content %}
 

templates/leads/lead_list.html
{% extends 'base.html' %}

{% block content %}

<section class="text-gray-600 body-font">
  <div class="container px-5 pt-24 mx-auto flex flex-wrap">
    <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
        <div>
            <h1 class="text-4xl text-gray-800">Leads</h1>
            <a href="{% url 'leads:category-list' %}" class="text-gray-500 hover:text-blue-500 py-10" href="{% url 'leads:create_lead' %}">Categories</a>
        </div>
        <div>
        {% if request.user.is_organiser %}
          <a class="text-gray-500 hover:text-blue-500" href="{% url 'leads:create_lead' %}">Create Lead</a>
        {% else %}
          <p class="text-gray-500" >Organisation: {{organisation}}</p>

        {% endif %}
            
        </div>
    </div>
  </div>
</section>


  <section class="text-gray-600 body-font">
        <div class="container mx-auto">
          <div class="flex flex-col text-center w-full mb-20">
            <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Assigned Leads</h1>
            <p class="lg:w-2/3 mx-auto leading-relaxed text-base">This tables show the leads that are being followed up by the agents from the current organisation</p>
          </div>
          <div class="container px-24 mx-auto">
            <table class="table-auto w-full text-left whitespace-no-wrap">
              <thead>
                <tr>
                  <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">S/N</th>
                  <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">First Name</th>
                  <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Last Name</th>
                  <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Age</th>
                  <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Agent</th>
                  <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Organisation</th>
                  <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Category</th>
                 
                  <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Phone</th>
                  <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">email</th>
                  <th class="w-10 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tr rounded-br"></th>
                </tr>
              </thead>
              <tbody>
              {% for lead in leads %}
                <tr>
                  {% comment %} <td class="px-4 py-3">Start</td>
                  <td class="px-4 py-3">5 Mb/s</td>
                  <td class="px-4 py-3">15 GB</td> {% endcomment %}
                  <td class="px-4 py-3 text-lg text-gray-900">{{forloop.counter}}</td>

                  <td class="px-4 py-3 text-lg text-gray-900">{{lead.first_name}}</td>
                  <td class="px-4 py-3 text-lg text-gray-900">{{lead.last_name}}</td>
                  <td class="px-4 py-3 text-lg text-gray-900">{{lead.age}}</td>
                  <td class="px-4 py-3 text-lg text-gray-900">{{lead.agent}}</td>
                  <td class="px-4 py-3 text-lg text-gray-900">{{lead.organisation}}</td>
                  {% if lead.category %}
                  <td class="px-4 py-3 text-lg text-gray-900">{{lead.category}}</td>
                  {% else %}
                  <td class="px-4 py-3 text-lg ">NAN</td>
                  {% endif %}
                  <td class="px-4 py-3 text-lg text-gray-900">{{lead.phone_number}}</td>
                  <td class="px-4 py-3 text-lg text-gray-900">{{lead.email}}</td>
                  
                  <td class="w-10 text-center">
                    <a class="text-blue-500"href="{% url 'leads:lead_detail' lead.pk %}">View</a>
                  </td>
                </tr>
              {% endfor %}
              
              </tbody>
            </table>
          </div>
    
      </section>

{% if unassigned_leads.exists %}
<section class="text-gray-600 body-font">
  <div class="container px-5 pt-24 mx-auto flex flex-wrap">
    <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
        <div>
            <h1 class="text-4xl text-gray-800">Unassigned Leads</h1>
        </div>
        <div>
       
            
        </div>
    </div>
  </div>
</section>





    
      {% for lead in unassigned_leads %}
      <div class="p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
          <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{lead.first_name}} {{lead.last_name}}</h2>
            <p class="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.</p>
            <a href="{% url 'leads:assign-lead' lead.pk%}" class="mt-3 text-indigo-500 inline-flex items-center">Assign Lead
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
    {% endfor %}

    {% endif %}

{% endblock content %}

templates/leads/leads_update.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto ">
      <div class="lg:w-1/1 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">Lead</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{lead.first_name}} {{lead.last_name}}</h1>
        <div class="flex mb-4">
          <a href="{% url 'leads:lead_detail' lead.pk%}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Overview</a>
          <a href="{% url 'leads:category-update' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Category</a>
          <a href="{% url 'leads:lead_update' lead.pk%}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Update</a>
        </div>
        <p class="leading-relaxed mb-4">austin listicle pour-over, neutra jean.</p>
      
            <form method='post'>
            {% csrf_token %}
            {{form|crispy}}
             <button class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 my-1 rounded-md">Update Lead</button>
            </form>
                
        <div class="flex">
          <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Button</button>
        
        </div>
      </div>
    </div>
  </div>
</section>



{% endblock content %}