agents/urls.py
from django.urls import path
from .views import (
    AgentListView,
    AgentDetailView, 
    AgentUpdateView,
    AgentCreateView,
    AgentDeleteView
)

app_name = 'agents'

urlpatterns = [
    path('', AgentListView.as_view(), name='agent_list'),
    path('create/', AgentCreateView.as_view(), name='agent_create'),
    path('detail/<int:pk>/', AgentDetailView.as_view(), name='agent_detail'),
    path('update/<int:pk>/', AgentUpdateView.as_view(), name='agent_update'),
    path('delete<int:pk>/', AgentDeleteView.as_view(), name='agent_delete')
]

dj_crm/urls.py
from django.contrib.auth.views import (LoginView, 
LogoutView, 
PasswordResetView,
PasswordResetDoneView,
PasswordResetCompleteView,
PasswordResetConfirmView,
)
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from leads.views import SignupView, home_page



urlpatterns = [
    path('', home_page, name='home'),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset-password', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-complete', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('signup/', SignupView.as_view(), name='signup')
]


if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

leads/urls.py
from django.urls import path
from .views import (
    LeadListView,
    LeadDetailView,
    LeadCreateView,
    LeadUpdateView,
    LeadDeleteView,
    AssignAgentView,
    CategoryListView,
    CategoryDetailView,
    CategoryUpdateView,
  

) 
app_name = 'leads'

urlpatterns = [


    path('', LeadListView.as_view(), name='lead_list'),
    path('<int:pk>/', LeadDetailView.as_view(), name='lead_detail'),
    path('update/<int:pk>/', LeadUpdateView.as_view(), name='lead_update'),
    path('delete/<int:pk>/', LeadDeleteView.as_view(), name='lead_delete'),
    path('assign-lead/<int:pk>/', AssignAgentView.as_view(), name='assign-lead'),
    path('create/', LeadCreateView.as_view(), name='create_lead'),
    path('category-list/', CategoryListView.as_view(), name='category-list'),
    path('<int:pk>/category-detail/', CategoryDetailView.as_view(), name='category-detail'),
    path('<int:pk>/category-update/', CategoryUpdateView.as_view(), name='category-update'),

]

templates/utils/navigation.html
<header class="text-gray-600 body-font">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
      </svg>
      <span class="ml-3 text-xl">DJ-CRM</span>
    </a>
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
    {% if request.user.is_authenticated %} 
      {% if request.user.is_organiser %}
       <a href="{% url 'agents:agent_list' %}" class="mr-5 hover:text-gray-900">Agents</a>
      {% endif %}
      <a href="{% url 'leads:lead_list' %}" class="mr-5 hover:text-gray-900">Leads</a>
      

      <p class="mr-3">Welcome {{request.user.username}}!!</p> 
      <button class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0"><a href="{% url 'logout' %}">Logout</a> 
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </button>
    {% else %}
    <a href="{% url 'signup' %}" class="mr-5 hover:text-gray-900">Signup</a>

      <button class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0"><a href="{% url 'login' %}">Login</a> 
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </button>
    {% endif %}
      
    </nav>

  </div>
</header>